# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_report:
    runs-on: ubuntu-latest
    name: Build Datapane report
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          # Use in-project so we don't have to mess around querying for the env name for the path
          virtualenvs-in-project: true

      - name: Poetry Install
        run: |
          poetry install

      - name: Global Activate Venv
        uses: actions/github-script@v6
        with:
          script: |
            // register the venv to future steps
            core.exportVariable('VIRTUAL_ENV', `${process.cwd()}/.venv`);
            // Configure the venv path so we can use the correct python.
            core.addPath(`${process.cwd()}/.venv/bin`);

      - uses: datapane/build-action@v2
        with:
          script: "reports/dp_script.py"
          token: ${{ secrets.TOKEN }}
